# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Env
        run: |
          sudo apt update -qq -y
          sudo apt-get install -qq -y python2.7-dev virtualenv python-pip python3-dev python3-pip libfreetype6-dev liblcms2-dev make libreoffice libreoffice-script-provider-python
          sudo apt-get autoremove -qq -y
          sudo apt-get autoclean -qq -y
          mkdir -p buildout-cache/{eggs,downloads}
          mkdir $HOME/tmp
          chmod 777 $HOME/tmp
          export TMPDIR=$HOME/tmp
          make startlibreoffice
  test:
    needs: setup
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        PLONE_VERSION: [ 4.3, 5.1, 5.2 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache eggs
        uses: actions/cache@v2
        env:
          cache-name: cache-eggs
        with:
          path: ./buildout-cache/eggs ./eggs
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.PLONE_VERSION }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.PLONE_VERSION }}
      - name: buildout
        run: |
          sed -ie "s#plone-5#plone-${{matrix.PLONE_VERSION}}#" test-ci.cfg
          virtualenv -p `which python` .
          bin/pip install -r requirements.txt coverage==5.3.1
          bin/buildout -c test-ci.cfg annotate
          bin/buildout -c test-ci.cfg
          bin/translation-manage -c
      - name: code-analysis
        run: |
          bin/code-analysis
      - name: test
        run: |
          bin/coverage run bin/test --test=\!"robot"
  coveralls:
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - name: Install Coveralls
        run: |
          sudo apt-get purge -qqy python2.7-dev virtualenv python-pip
          sudo apt-get install -qqy python3-dev python3-pip
          rm -rf ~/.cache/pip
          pip install -U pip setuptools "coveralls>=3.0.0" --no-cache-dir
      - name: Publish to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
